import { useEffect, useState } from 'react'
import { ArrowLeft, Ban, Building2, CalendarDays, CheckCircle2, Mail, MapPin, MessageCircle, Package, Phone, ShieldAlert, Star, UserRoundCheck } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { adminService } from '../../services/mockAdminService.js'
import { PageHeader, StatusBadge } from '../components/ui.jsx'

export function MerchantDetailPage() {
  const { userId } = useParams()
  const navigate = useNavigate()
  const [user, setUser] = useState(null)
  const [busy, setBusy] = useState(false)
  useEffect(() => { adminService.getUser(userId).then(setUser) }, [userId])
  const updateStatus = async (status) => { setBusy(true); const nextUser = await adminService.updateUserStatus(user.id, status); setUser({ ...nextUser }); setBusy(false); toast.success(status === 'active' ? 'Le compte et la boutique ont été validés.' : 'Le compte a été suspendu.') }
  if (!user) return <div className="h-80 animate-pulse rounded-2xl bg-base-200" />
  if (!user.shop) return <div className="card p-6 text-center"><p className="font-semibold text-base-content">Ce compte ne possède pas de boutique.</p><button onClick={() => navigate('/admin/utilisateurs')} className="mt-4 text-sm font-semibold text-brand">Retour aux utilisateurs</button></div>
  const { shop } = user
  return <>
    <Link to="/admin/utilisateurs" className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-base-content/60 transition hover:text-brand"><ArrowLeft size={17} /> Retour aux utilisateurs</Link>
    <PageHeader eyebrow="Fiche commerçant" title={`${user.firstName} ${user.lastName}`} description="Informations du compte et de la boutique." action={<StatusBadge status={user.status} />} />
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-4">
      <section className="card overflow-hidden"><div className="h-20 bg-brand" /><div className="relative px-4 pb-5 sm:px-5"><span className="-mt-9 grid size-[72px] place-items-center rounded-lg border-4 border-white bg-brand/10 text-lg font-bold text-brand">{user.initials}</span><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold text-base-content">{user.firstName} {user.lastName}</h2><UserRoundCheck size={18} className="text-brand" /></div><p className="mt-1 text-sm text-base-content/55">Compte créé le {user.joinedAt}</p></div><StatusBadge status={user.status} /></div><div className="mt-5 grid gap-4 border-t border-base-200 pt-4 sm:grid-cols-2"><Contact icon={Mail} label="Adresse e-mail" value={user.email} /><Contact icon={Phone} label="Téléphone" value={user.phone} /><Contact icon={MapPin} label="Localisation" value={user.location} /><Contact icon={CalendarDays} label="Dernière activité" value={user.lastActive} /></div></div></section>
      <section className="card p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-wide text-accent">BOUTIQUE</p><h2 className="mt-1 text-xl font-bold text-base-content">{shop.name}</h2><p className="mt-1 text-sm text-base-content/55">{shop.category}</p></div><span className="grid size-9 place-items-center rounded-lg bg-brand/10 text-brand"><Building2 size={19} /></span></div><p className="mt-4 text-sm leading-6 text-base-content/70">{shop.description}</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric icon={Package} value={shop.products} label="Produits" /><Metric icon={MessageCircle} value={shop.messages} label="Messages" /><Metric icon={Star} value={shop.rating || '—'} label="Note / 5" /><Metric icon={Building2} value={shop.views} label="Vues" /></div><div className="mt-5 flex items-center justify-between border-t border-base-200 pt-4"><span className="text-sm text-base-content/55">Créée le {shop.createdAt}</span><StatusBadge status={shop.status} /></div></section>
    </div><aside className="space-y-4"><section className="card p-4"><h2 className="font-semibold text-base-content">Actions de modération</h2><p className="mt-1 text-sm leading-5 text-base-content/55">Ces actions seront reliées aux permissions du backend.</p><div className="mt-4 space-y-2">{user.status !== 'active' && <button disabled={busy} onClick={() => updateStatus('active')} className="flex w-full items-center justify-center gap-2 rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-soft disabled:opacity-60"><CheckCircle2 size={17} /> Valider le compte</button>}{user.status !== 'suspended' && <button disabled={busy} onClick={() => updateStatus('suspended')} className="flex w-full items-center justify-center gap-2 rounded-lg border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-semibold text-rose-700 transition hover:bg-rose-100 disabled:opacity-60"><Ban size={17} /> Suspendre le compte</button>}</div></section><section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><ShieldAlert className="shrink-0 text-amber-700" size={19} /><div><h2 className="font-semibold text-amber-900">Historique</h2><p className="mt-1 text-sm leading-5 text-amber-800/80">Aucune sanction active. Les décisions seront journalisées par l’API.</p></div></div></section></aside></div>
  </>
}

function Contact({ icon: Icon, label, value }) { return <div className="flex gap-3"><span className="mt-0.5 text-brand"><Icon size={17} /></span><div><p className="text-xs font-semibold text-base-content/45">{label}</p><p className="mt-0.5 break-all text-sm font-medium text-base-content/80">{value}</p></div></div> }
function Metric({ icon: Icon, value, label }) { return <div className="rounded-lg bg-base-100 p-3"><Icon size={16} className="text-brand" /><p className="mt-2 text-lg font-bold text-base-content">{value}</p><p className="text-xs font-medium text-base-content/55">{label}</p></div> }